# Generated by Django 4.1 on 2022-09-03 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2022, 9, 3, 22, 26, 24, 713864, tzinfo=datetime.timezone.utc))),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('message', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 9, 3, 22, 26, 24, 713864, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
